// Generated by scripts/generate-posthog-config.js — do not edit on deploy.
window.FONSECA_POSTHOG_CONFIG = {
    "key": "phc_vyAcaKJofYZisiUWaUw5oRcuAtE3JMCvd7AxgMYG7vbB",
    "api_host": "https://us.i.posthog.com"
};
